export const graphConfig = {
  labelMaxLength: 22,
  labelOffset: 8,
  minLabelFontSize: 7,
  minLabelVisibleZoom: 0.7,
  labelScreenScale: 0.82,
  labelFontWeight: 400,
  minCanvasScale: 0.001,
  defaultWidth: 800,
  defaultHeight: 600,
  centerForceStrength: 0.5,
  chargeDistanceMax: 240,
  particleWidth: 1.4,
  pointerPadding: 6,
  hoverLeaveDelay: 60,
  zoomToFitDuration: 400,
  zoomToFitDelay: 800,
  zoomToFitPadding: 40,
  newNodeJitter: 12,
} as const;
