version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod

    volumes:
      - ~/frontend-build:/app/dist
      - ~/frontend-build/builds:/app/dist/builds/

    environment:
      - API_URL=${API_URL}
