FROM node:16-alpine3.15
USER root
RUN npm install -g @quasar/cli && \
    npm install -g @vue/cli && \
    npm install -g @vue/cli-init

WORKDIR /app

COPY yarn.lock package.json ./
RUN yarn install --frozen-lockfile

RUN ls
COPY . .

CMD ["yarn", "build"]
