#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# TODO: feat/stable-beta uncomment
# ./deploy/sync-capaticor-version.sh
bun install --package-lock-only --no-scripts && git add bun.lock
# git add quasar.config.ts src-capacitor/android/app/build.gradle
