name: Build quasar app

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
      - name: Install dependencies
        run: yarn global add @quasar/cli && yarn
      - name: Build
        run: yarn build
