name: CI/CD second brain client

on: [push, pull_request]

env:
  API_URL: ${{ vars.API_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
      - name: Install dependencies
        run: yarn global add @quasar/cli && yarn
      - name: Build
        run: yarn build

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, lint]
    environment: deploy
    steps:
      - name: List environment variables
        run: env
      - name: ssh deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ${{ secrets.SSH_TARGET }}
            ls
            eval $(ssh-agent -s)
            ssh-add ~/.ssh/sb-client
            cd ~/second-brain/second-brain-client

            cat <<EOT > .env
            DEUBG=true
            API_URL=${{ env.API_URL }}
            EOT
            git checkout master
            git fetch --all
            git reset --hard origin/master
            docker system prune -f
            docker-compose up --build
          args: '-tt -vvv'
