name: CI/CD orgnote client

on: [push, pull_request]

env:
  API_URL: ${{ vars.API_URL }}

jobs:
  check_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          allowed-commit-types: 'feat,fix,chore,release,refactor' 

  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Node.js dependencies
        run: bun install --frozen-lockfile

      - name: Run linters
        run: bun run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check_commit, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun add global @quasar/cli
      - name: Build
        run: bun run build

  build_ssr:
    name: Build ssr
    runs-on: ubuntu-latest
    needs: [check_commit, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          bun install --frozen-lockfile
          bun add global @quasar/cli
      - name: Build ssr
        run: bun run build -m ssr


  code-quality:
    name: Check code quality
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Node.js dependencies
        run: bun install --frozen-lockfile

      - name: Run duplicates check
        run: bun run report:duplicates

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Node.js dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test


  push_client_image:
    name: Push client image
    runs-on: ubuntu-latest
    needs: [build, build_ssr]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            dockerfile: Dockerfile.ssr
            push: true
            tags: orgnote/client:latest
  release:
    name: Create release
    needs: [build, lint, tests, code-quality]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        uses: justincy/github-action-npm-release@2.0.2
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Print release output
        if: ${{ steps.release.outputs.released == 'true' }}
        run: echo Release ID ${{ steps.release.outputs.release_id }}
