on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-android:
    name: Build Android APK
    needs: [get-version]
    uses: ./.github/workflows/build-android.yaml
    with:
      environment: deploy
      version: ${{ github.event.release.tag_name || needs.get-version.outputs.version }}
      prerelease: false

  upload-release-asset:
    name: Upload Release Asset
    needs: [build-android, get-version]
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: orgnote-${{ github.event.release.tag_name || needs.get-version.outputs.version }}.apk
          path: ./dist/capacitor/android/apk/release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/capacitor/android/apk/release/orgnote-${{ github.event.release.tag_name || needs.get-version.outputs.version }}.apk
          asset_name: orgnote-${{ github.event.release.tag_name || needs.get-version.outputs.version }}.apk
          asset_content_type: application/octet-stream
